name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew build
    - name: Test with gradle
      run: ./gradlew check
    - name: Code Climate upload test coverage
      env:
        CC_TEST_REPORTER_ID: 426a8cba7a9651be2761a6f78bd46e622c0c4e2dd7d611e21b57154ff97ba5cc
        JACOCO_SOURCE_PATH: src/main/kotlin
      run: |
        export GIT_COMMIT_SHA=${GITHUB_SHA}
        export GIT_BRANCH=${GITHUB_REF#refs/heads/}
        wget -O cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        chmod +x cc-test-reporter
        ./cc-test-reporter before-build
        ./gradlew jacocoTestReport
        ./cc-test-reporter format-coverage build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
        ./cc-test-reporter upload-coverage
