name: JS tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: __
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build
        run: chmod +x gradlew && ./gradlew assemble
      - name: Launch tests
        run: ./gradlew jsTest